### PR TITLE
blobstore interface update

### PR DESCRIPTION
**Pull request by stevelr**
- merged updates from @matsbror  https://github.com/wasmCloud/interfaces/pull/55
- updated apis to support AWS S3

Signed-off-by: stevelr <steve@cosmonic.com>

### CODE REVIEW

**Comment by stevelr** [comment]
Added contentLength, contentType, contentEncoding to putObjectRequest and GetObjectResponse.

If the provider can't easily determine contentType or contentEncoding, it can return None.

**Comment by stevelr** [comment]
Note for reviewers:
- Cargo.toml contains relative paths to wasmbus-rpc and weld-codegen as it depends on unmerged PRs https://github.com/wasmCloud/weld/pull/81 and https://github.com/wasmCloud/weld/pull/80

**Comment by stevelr** [comment]
@matsbror Please let me know if anything in here doesn't work for your FS provider. It won't compile out-of-the-box as it depends on some unmerged PRs which get addressed early Monday.

Draft PR of blobstore s3 capability provider (still in progress) https://github.com/wasmCloud/capability-providers/pull/137

**Comment by matsbror** [comment]
> @matsbror Please let me know if anything in here doesn't work for your FS provider. It won't compile out-of-the-box as it depends on some unmerged PRs which get addressed early Monday.

I will have a look in a few days as I am travelling at the moment.

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
